server:
  port: 8080
spring:
  application:
    name: employee
    config:
    import:
      configserver: http://localhost:8761/eureka

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/construction
    username: root
    password: noura

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true