server:
  port: 8880
spring:
  application:
    name: employee
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://construction-app-8728.7tc.aws-eu-central-1.cockroachlabs.cloud:26257/construction?sslmode=require&password=-J5_BzsUkoJWJprUrzrSGA&user=noura
    username: noura
    password: -J5_BzsUkoJWJprUrzrSGA

